# Generated by Django 3.2 on 2022-01-19 16:51

from django.db import migrations, models
import file_field_utils.db.fields
import file_field_utils.db.utils.backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('image', file_field_utils.db.fields.SVGAndImageField(blank=True, upload_to=file_field_utils.db.utils.backend.UploadPath('news'), verbose_name='Image')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
